import { readFile } from "node:fs/promises";
import { join, relative } from "node:path";
import type { Octokit } from "@octokit/rest";

export const BRANCH = "delta-cv/resume-update";

export interface PrResult {
  url: string;
  number: number;
  created: boolean;
}

export interface PrBody {
  summary: string;
  newCapabilities?: string[] | undefined;
  risingTags?: string[] | undefined;
  decliningTags?: string[] | undefined;
  error?: string | undefined;
}

/** Build the PR body markdown from structured sections. */
export function buildPrBody(body: PrBody): string {
  const lines: string[] = ["## Delta CV — Resume Update", ""];

  if (body.error) {
    lines.push("### Error", "", body.error, "");
  }

  lines.push("### Summary", "", body.summary, "");

  if (body.newCapabilities && body.newCapabilities.length > 0) {
    lines.push("### New Capabilities", "");
    for (const cap of body.newCapabilities) lines.push(`- ${cap}`);
    lines.push("");
  }

  if (body.risingTags && body.risingTags.length > 0) {
    lines.push("### Rising Trends", "");
    for (const tag of body.risingTags) lines.push(`- ${tag}`);
    lines.push("");
  }

  if (body.decliningTags && body.decliningTags.length > 0) {
    lines.push("### Declining Trends", "");
    for (const tag of body.decliningTags) lines.push(`- ${tag}`);
    lines.push("");
  }

  lines.push("---", "_Auto-generated by [Delta CV](https://github.com/delta-cv/delta)_");
  return lines.join("\n");
}

/** Get the SHA of the default branch's HEAD commit. */
async function getDefaultBranchSha(
  octokit: Octokit,
  owner: string,
  repo: string,
): Promise<{ sha: string; ref: string }> {
  const { data: repoData } = await octokit.repos.get({ owner, repo });
  const ref = `heads/${repoData.default_branch}`;
  const { data: refData } = await octokit.git.getRef({ owner, repo, ref });
  return { sha: refData.object.sha, ref: repoData.default_branch };
}

/** Create a blob for each file and return their tree entries. */
async function createBlobsForFiles(
  octokit: Octokit,
  owner: string,
  repo: string,
  files: Map<string, string>,
): Promise<Array<{ path: string; mode: "100644"; type: "blob"; sha: string }>> {
  const entries = [];
  for (const [path, content] of files) {
    const { data } = await octokit.git.createBlob({
      owner,
      repo,
      content,
      encoding: "utf-8",
    });
    entries.push({ path, mode: "100644" as const, type: "blob" as const, sha: data.sha });
  }
  return entries;
}

/**
 * Collect all non-.gitignored files under dataDir that have been modified.
 * Returns a map of repo-relative paths to their content.
 */
export async function collectChangedFiles(
  dataDir: string,
  repoRoot: string,
): Promise<Map<string, string>> {
  const { readdir, stat } = await import("node:fs/promises");
  const files = new Map<string, string>();

  async function walk(dir: string): Promise<void> {
    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(fullPath);
      } else if (entry.isFile()) {
        const relPath = relative(repoRoot, fullPath);
        const content = await readFile(fullPath, "utf8");
        files.set(relPath, content);
      }
    }
  }

  await walk(dataDir);
  return files;
}

/**
 * Create or update a PR with the given file changes on the resume-update branch.
 * If the branch already exists, appends a new commit. Otherwise creates the branch.
 */
export async function createOrUpdatePr(
  octokit: Octokit,
  owner: string,
  repo: string,
  files: Map<string, string>,
  body: PrBody,
  title: string,
): Promise<PrResult> {
  const { sha: baseSha } = await getDefaultBranchSha(octokit, owner, repo);

  // Check if branch exists
  let branchExists = false;
  let currentBranchSha = baseSha;
  try {
    const { data: refData } = await octokit.git.getRef({
      owner,
      repo,
      ref: `heads/${BRANCH}`,
    });
    branchExists = true;
    currentBranchSha = refData.object.sha;
  } catch {
    // Branch doesn't exist — will create it
  }

  // Get the current tree of the branch base
  const { data: baseCommit } = await octokit.git.getCommit({
    owner,
    repo,
    commit_sha: currentBranchSha,
  });

  // Create blobs and tree
  const treeEntries = await createBlobsForFiles(octokit, owner, repo, files);
  const { data: newTree } = await octokit.git.createTree({
    owner,
    repo,
    base_tree: baseCommit.tree.sha,
    tree: treeEntries,
  });

  // Create commit
  const commitMessage = branchExists
    ? "chore: update resume data (delta-cv)"
    : "chore: initial resume data (delta-cv)";
  const { data: newCommit } = await octokit.git.createCommit({
    owner,
    repo,
    message: commitMessage,
    tree: newTree.sha,
    parents: [currentBranchSha],
  });

  // Create or update the branch ref
  if (branchExists) {
    await octokit.git.updateRef({
      owner,
      repo,
      ref: `heads/${BRANCH}`,
      sha: newCommit.sha,
      force: true,
    });
  } else {
    await octokit.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${BRANCH}`,
      sha: newCommit.sha,
    });
  }

  // Find or create PR
  const { data: existingPrs } = await octokit.pulls.list({
    owner,
    repo,
    head: `${owner}:${BRANCH}`,
    state: "open",
  });

  const prBody = buildPrBody(body);

  if (existingPrs.length > 0) {
    const pr = existingPrs[0];
    if (!pr) throw new Error("Unexpected: PR list returned empty after length check");
    await octokit.pulls.update({
      owner,
      repo,
      pull_number: pr.number,
      title,
      body: prBody,
    });
    return { url: pr.html_url, number: pr.number, created: false };
  }

  // Get default branch name for PR base
  const { data: repoData } = await octokit.repos.get({ owner, repo });
  const { data: newPr } = await octokit.pulls.create({
    owner,
    repo,
    title,
    head: BRANCH,
    base: repoData.default_branch,
    body: prBody,
  });

  return { url: newPr.html_url, number: newPr.number, created: true };
}

/** Create an issue with error details when the action fails. */
export async function createErrorIssue(
  octokit: Octokit,
  owner: string,
  repo: string,
  error: Error,
): Promise<string> {
  const title = `Delta CV pipeline failed: ${error.message.slice(0, 80)}`;
  const body = [
    "## Delta CV — Pipeline Error",
    "",
    "The Delta CV pipeline encountered an error during execution.",
    "",
    "### Error",
    "",
    "```",
    error.stack ?? error.message,
    "```",
    "",
    "### Troubleshooting",
    "",
    "- Verify `LLM_API_KEY` is set in repository secrets",
    "- Check that `config.json` has a valid `login` field",
    "- Review the [Action logs](../actions) for more details",
    "",
    "---",
    "_Auto-generated by [Delta CV](https://github.com/delta-cv/delta)_",
  ].join("\n");

  // Check for existing open error issues to avoid duplicates
  const { data: existingIssues } = await octokit.issues.list({
    owner,
    repo,
    labels: "delta-cv-error",
    state: "open",
    per_page: 1,
  });

  if (existingIssues.length > 0) {
    const issue = existingIssues[0];
    if (!issue) throw new Error("Unexpected: issue list returned empty after length check");
    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: issue.number,
      body: `### New failure\n\n\`\`\`\n${error.stack ?? error.message}\n\`\`\``,
    });
    return issue.html_url;
  }

  const { data: issue } = await octokit.issues.create({
    owner,
    repo,
    title,
    body,
    labels: ["delta-cv-error"],
  });

  return issue.html_url;
}
