import { execSync } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

// ── Mock Octokit ─────────────────────────────────────────────────────────────

const mockOctokit = {
  repos: { get: vi.fn() },
  git: {
    getRef: vi.fn(),
    getCommit: vi.fn(),
    createBlob: vi.fn(),
    createTree: vi.fn(),
    createCommit: vi.fn(),
    createRef: vi.fn(),
    updateRef: vi.fn(),
  },
  pulls: { list: vi.fn(), create: vi.fn(), update: vi.fn() },
  issues: { list: vi.fn(), create: vi.fn(), createComment: vi.fn() },
};

vi.mock("@octokit/rest", () => ({
  Octokit: vi.fn().mockImplementation(() => mockOctokit),
}));

// ── Imports (after mocks) ────────────────────────────────────────────────────

import { buildPrBody, createErrorIssue, createOrUpdatePr } from "../src/core/github/pr.ts";
import { initRepo } from "../src/core/init.ts";

// ── Helpers ──────────────────────────────────────────────────────────────────

let tmpDir: string;

beforeEach(async () => {
  tmpDir = join(tmpdir(), `delta-m4-test-${Date.now()}`);
  await mkdir(tmpDir, { recursive: true });
  vi.clearAllMocks();
});

afterEach(async () => {
  await rm(tmpDir, { recursive: true, force: true });
});

// ── buildPrBody ──────────────────────────────────────────────────────────────

describe("buildPrBody", () => {
  it("renders summary section", () => {
    const body = buildPrBody({ summary: "Processed 10 events" });
    expect(body).toContain("## Delta CV — Resume Update");
    expect(body).toContain("### Summary");
    expect(body).toContain("Processed 10 events");
    expect(body).toContain("Auto-generated by");
  });

  it("renders new capabilities when provided", () => {
    const body = buildPrBody({
      summary: "Update",
      newCapabilities: ["TypeScript", "React"],
    });
    expect(body).toContain("### New Capabilities");
    expect(body).toContain("- TypeScript");
    expect(body).toContain("- React");
  });

  it("renders rising and declining tags", () => {
    const body = buildPrBody({
      summary: "Update",
      risingTags: ["rust"],
      decliningTags: ["python"],
    });
    expect(body).toContain("### Rising Trends");
    expect(body).toContain("- rust");
    expect(body).toContain("### Declining Trends");
    expect(body).toContain("- python");
  });

  it("renders error section when present", () => {
    const body = buildPrBody({ summary: "Failed", error: "LLM_API_KEY missing" });
    expect(body).toContain("### Error");
    expect(body).toContain("LLM_API_KEY missing");
  });

  it("omits optional sections when empty", () => {
    const body = buildPrBody({ summary: "OK" });
    expect(body).not.toContain("### New Capabilities");
    expect(body).not.toContain("### Rising Trends");
    expect(body).not.toContain("### Declining Trends");
    expect(body).not.toContain("### Error");
  });
});

// ── createOrUpdatePr ─────────────────────────────────────────────────────────

describe("createOrUpdatePr", () => {
  function setupMocks(opts: { branchExists: boolean; existingPr?: { number: number } }) {
    mockOctokit.repos.get.mockResolvedValue({
      data: { default_branch: "main" },
    });
    mockOctokit.git.getRef.mockImplementation((params: { ref: string }) => {
      if (params.ref === "heads/delta-cv/resume-update") {
        if (opts.branchExists) {
          return Promise.resolve({ data: { object: { sha: "existing-sha" } } });
        }
        return Promise.reject(new Error("Not found"));
      }
      // Default branch ref lookup
      return Promise.resolve({ data: { object: { sha: "base-sha" } } });
    });
    mockOctokit.git.getCommit.mockResolvedValue({
      data: { tree: { sha: "tree-sha" } },
    });
    mockOctokit.git.createBlob.mockResolvedValue({ data: { sha: "blob-sha" } });
    mockOctokit.git.createTree.mockResolvedValue({ data: { sha: "new-tree-sha" } });
    mockOctokit.git.createCommit.mockResolvedValue({ data: { sha: "commit-sha" } });
    mockOctokit.git.createRef.mockResolvedValue({});
    mockOctokit.git.updateRef.mockResolvedValue({});

    if (opts.existingPr) {
      mockOctokit.pulls.list.mockResolvedValue({
        data: [
          {
            number: opts.existingPr.number,
            html_url: `https://github.com/test/repo/pull/${opts.existingPr.number}`,
          },
        ],
      });
      mockOctokit.pulls.update.mockResolvedValue({});
    } else {
      mockOctokit.pulls.list.mockResolvedValue({ data: [] });
      mockOctokit.pulls.create.mockResolvedValue({
        data: { html_url: "https://github.com/test/repo/pull/1", number: 1 },
      });
    }
  }

  it("creates a new branch and PR when branch doesn't exist", async () => {
    setupMocks({ branchExists: false });
    const files = new Map([["data/test.json", '{"test":true}']]);
    const result = await createOrUpdatePr(
      mockOctokit as unknown as import("@octokit/rest").Octokit,
      "test",
      "repo",
      files,
      { summary: "Test" },
      "Test PR",
    );

    expect(result.created).toBe(true);
    expect(result.number).toBe(1);
    expect(result.url).toContain("pull/1");
    expect(mockOctokit.git.createRef).toHaveBeenCalledWith(
      expect.objectContaining({ ref: "refs/heads/delta-cv/resume-update" }),
    );
    expect(mockOctokit.pulls.create).toHaveBeenCalled();
  });

  it("updates existing PR when branch and PR exist", async () => {
    setupMocks({ branchExists: true, existingPr: { number: 5 } });
    const files = new Map([["data/test.json", '{"test":true}']]);
    const result = await createOrUpdatePr(
      mockOctokit as unknown as import("@octokit/rest").Octokit,
      "test",
      "repo",
      files,
      { summary: "Update" },
      "Update PR",
    );

    expect(result.created).toBe(false);
    expect(result.number).toBe(5);
    expect(mockOctokit.pulls.update).toHaveBeenCalledWith(
      expect.objectContaining({ pull_number: 5 }),
    );
    expect(mockOctokit.git.updateRef).toHaveBeenCalled();
  });
});

// ── createErrorIssue ─────────────────────────────────────────────────────────

describe("createErrorIssue", () => {
  it("creates a new issue when no existing error issues", async () => {
    mockOctokit.issues.list.mockResolvedValue({ data: [] });
    mockOctokit.issues.create.mockResolvedValue({
      data: { html_url: "https://github.com/test/repo/issues/1" },
    });

    const url = await createErrorIssue(
      mockOctokit as unknown as import("@octokit/rest").Octokit,
      "test",
      "repo",
      new Error("something failed"),
    );

    expect(url).toContain("issues/1");
    expect(mockOctokit.issues.create).toHaveBeenCalledWith(
      expect.objectContaining({
        title: expect.stringContaining("something failed"),
        labels: ["delta-cv-error"],
      }),
    );
  });

  it("adds comment to existing open error issue", async () => {
    mockOctokit.issues.list.mockResolvedValue({
      data: [{ number: 3, html_url: "https://github.com/test/repo/issues/3" }],
    });
    mockOctokit.issues.createComment.mockResolvedValue({});

    const url = await createErrorIssue(
      mockOctokit as unknown as import("@octokit/rest").Octokit,
      "test",
      "repo",
      new Error("another failure"),
    );

    expect(url).toContain("issues/3");
    expect(mockOctokit.issues.createComment).toHaveBeenCalled();
    expect(mockOctokit.issues.create).not.toHaveBeenCalled();
  });
});

// ── initRepo ─────────────────────────────────────────────────────────────────

describe("initRepo", () => {
  it("scaffolds template files into target directory", async () => {
    const target = join(tmpDir, "my-resume");
    const result = await initRepo(target);

    expect(result.dir).toBe(target);
    expect(result.files.length).toBeGreaterThan(0);

    // Check key files exist
    expect(existsSync(join(target, "config.json"))).toBe(true);
    expect(existsSync(join(target, "README.md"))).toBe(true);
    expect(existsSync(join(target, ".gitignore"))).toBe(true);
    expect(existsSync(join(target, ".github", "workflows", "delta.yml"))).toBe(true);
    expect(existsSync(join(target, "data", "_meta", ".gitkeep"))).toBe(true);

    // Check git repo was initialized
    expect(existsSync(join(target, ".git"))).toBe(true);

    // Check config.json has placeholder
    const config = JSON.parse(await readFile(join(target, "config.json"), "utf8"));
    expect(config.login).toBe("YOUR_GITHUB_LOGIN");
  });

  it("rejects non-empty existing directory", async () => {
    const target = join(tmpDir, "existing");
    await mkdir(target, { recursive: true });
    await writeFile(join(target, "some-file.txt"), "content");

    await expect(initRepo(target)).rejects.toThrow("already exists and is not empty");
  });

  it("allows empty existing directory", async () => {
    const target = join(tmpDir, "empty-dir");
    await mkdir(target, { recursive: true });

    const result = await initRepo(target);
    expect(existsSync(join(result.dir, "config.json"))).toBe(true);
  });
});
