/** Canonical technology / capability tags used throughout the tagging pipeline. */
export const TAG_VOCAB = [
  // Languages
  "typescript",
  "javascript",
  "python",
  "rust",
  "go",
  "java",
  "kotlin",
  "swift",
  "c",
  "cpp",
  "csharp",
  "ruby",
  "php",
  "scala",
  "elixir",
  // Runtimes & platforms
  "nodejs",
  "deno",
  "bun",
  "browser",
  "edge-runtime",
  "react-native",
  "electron",
  // Frontend
  "react",
  "vue",
  "svelte",
  "angular",
  "nextjs",
  "nuxtjs",
  "astro",
  "css",
  "tailwind",
  "webassembly",
  // Backend
  "express",
  "fastify",
  "nestjs",
  "hono",
  "graphql",
  "rest-api",
  "grpc",
  "websocket",
  // Data
  "postgresql",
  "mysql",
  "sqlite",
  "mongodb",
  "redis",
  "elasticsearch",
  "prisma",
  "drizzle",
  // Infrastructure
  "docker",
  "kubernetes",
  "terraform",
  "aws",
  "gcp",
  "azure",
  "cloudflare",
  "vercel",
  "github-actions",
  "ci-cd",
  // AI/ML
  "llm",
  "openai",
  "pytorch",
  "tensorflow",
  "rag",
  "embeddings",
  "langchain",
  // Cross-cutting
  "testing",
  "security",
  "performance",
  "observability",
  "accessibility",
  "open-source",
  "architecture",
  "api-design",
  "code-review",
  "documentation",
] as const;

export type Tag = (typeof TAG_VOCAB)[number];
