import type { ResumeDraft } from "../schema/agent.ts";

function formatPeriod(from: string, to: string): string {
  const f = from.slice(0, 7);
  const t = to.slice(0, 7);
  return f === t ? f : `${f} ~ ${t}`;
}

/**
 * Render a ResumeDraft into clean Markdown that matches real resume conventions.
 * Produces: headline, summary, skills (grouped), selected projects, other experience.
 */
export function renderResumeDraftMarkdown(draft: ResumeDraft): string {
  const lines: string[] = [];

  lines.push(`# ${draft.login}`);
  lines.push("");
  lines.push(`**${draft.headline}**`);
  lines.push("");

  lines.push("## Summary");
  lines.push("");
  lines.push(draft.summary);
  lines.push("");

  if (draft.skills.length > 0) {
    lines.push("## Skills");
    lines.push("");
    for (const group of draft.skills) {
      lines.push(`**${group.category}**: ${group.items.join(", ")}`);
      lines.push("");
    }
  }

  if (draft.selectedProjects.length > 0) {
    lines.push("## Projects");
    lines.push("");
    for (const project of draft.selectedProjects) {
      const period = formatPeriod(project.period.from, project.period.to);
      lines.push(`### ${project.title}`);
      lines.push("");
      lines.push(`\`${period}\` · ${project.stack.slice(0, 5).join(", ")}`);
      lines.push("");
      for (const bullet of project.bullets) {
        lines.push(`- ${bullet}`);
      }
      lines.push("");
    }
  }

  if (draft.otherExperience.length > 0) {
    lines.push("## Other Experience");
    lines.push("");
    for (const item of draft.otherExperience) {
      lines.push(`- ${item}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by Delta CV · ${draft.generatedAt.slice(0, 10)}*`);
  lines.push("");

  return lines.join("\n");
}
