import type { ResumeDraft } from "../schema/agent.ts";

export interface ResumeTemplateLabels {
  summary: string;
  skills: string;
  projects: string;
  otherExperience: string;
  github: string;
  generatedBy: string;
}

export interface ResumeTemplateData {
  lang: "zh" | "en";
  login: string;
  headline: string;
  summary: string;
  generatedDate: string;
  labels: ResumeTemplateLabels;
  skills: Array<{
    category: string;
    items: string[];
    itemsText: string;
  }>;
  selectedProjects: Array<{
    projectId: string;
    title: string;
    period: string;
    stack: string[];
    stackText: string;
    bullets: string[];
  }>;
  otherExperience: string[];
}

const ZH_RE = /[\u3400-\u9fff]/;

function detectDraftLanguage(draft: ResumeDraft): "zh" | "en" {
  const sample = [
    draft.headline,
    draft.summary,
    ...draft.skills.map((skill) => skill.category),
  ].join(" ");
  return ZH_RE.test(sample) ? "zh" : "en";
}

function labelsFor(lang: "zh" | "en"): ResumeTemplateLabels {
  if (lang === "zh") {
    return {
      summary: "总结",
      skills: "技能",
      projects: "项目经历",
      otherExperience: "其他经历",
      github: "GitHub",
      generatedBy: "Generated by Delta CV",
    };
  }
  return {
    summary: "Summary",
    skills: "Skills",
    projects: "Projects",
    otherExperience: "Other Experience",
    github: "GitHub",
    generatedBy: "Generated by Delta CV",
  };
}

/**
 * Stable template-facing view model for HTML renderers.
 * Templates should consume this instead of reaching into ResumeDraft directly.
 */
export function buildResumeTemplateData(draft: ResumeDraft): ResumeTemplateData {
  const lang = detectDraftLanguage(draft);
  return {
    lang,
    login: draft.login,
    headline: draft.headline,
    summary: draft.summary,
    generatedDate: draft.generatedAt.slice(0, 10),
    labels: labelsFor(lang),
    skills: draft.skills.map((group) => ({
      category: group.category,
      items: group.items,
      itemsText: group.items.join(", "),
    })),
    selectedProjects: draft.selectedProjects.map((project) => ({
      projectId: project.projectId,
      title: project.title,
      period:
        project.period.from.slice(0, 7) === project.period.to.slice(0, 7)
          ? project.period.from.slice(0, 7)
          : `${project.period.from.slice(0, 7)} – ${project.period.to.slice(0, 7)}`,
      stack: project.stack,
      stackText: project.stack.join(" · "),
      bullets: project.bullets,
    })),
    otherExperience: draft.otherExperience,
  };
}
